services:
  web:
    image: todoapp:1.0
    build: 
     context: .
     dockerfile: Dockerfile
    container_name: todoapp_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: unless-stopped
  
  mysql:
   image: my-sql:latest
   build:
     context: .
     dockerfile: Dockerfile.mysql
   container_name: my-sql
   ports:
     - "3306:3306"
   volumes:
     - db_data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=app_db
     - MYSQL_USER=app_user
     - MYSQL_PASSWORD=1234
   healthcheck:
     test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
     interval: 5s
     timeout: 5s
     retries: 5
    
volumes:
  db_data:

networks:
  todoapp_network:
    driver: bridge